---
title: FFR or IVUS to Guide PCI
format: revealjs
---

## Background

- CAD 환자의 PCI를 평가할 때, FFR이나 IVUS를 이용하여 재개통술 및 스텐트 삽입 여부를 결정할 수 있음
- 그러나, 이 두 가지 방법 중 하나만을 사용하여 모든 판단을 내렸을 때의 임상 결과 차이에 대해서는 아직 명확하지 않음

---

## Methods

- 중간 정도 협착(관상동맥조영술에서 시각적으로 폐색이 40-70%로 보이는 경우)의 치료를 위해 PCI를 평가받는 환자 1,682명을 무작위로 1:1 비율로 배정하여, FFR(혈류분획예비력) 기반 시술 또는 IVUS(혈관내 초음파) 기반 시술을 받도록 함
- FFR 또는 IVUS는 PCI 시행 여부와 PCI 성공 여부를 평가하는 데 사용

---

## Methods

- FFR 그룹에서는 FFR 값이 0.80 이하인 경우에만 PCI를 시행
- IVUS 그룹에서는 최소 내강 면적이 3mm² 이하이거나, 내강 면적이 3-4mm²이면서 죽상경화반 부하(plaque burden)가 70%를 초과할 경우 PCI를 시행
- 주요 평가 결과는 무작위 배정 후 24개월 이내에 발생한 사망 - 심근경색 - 재혈관화의 복합 결과
- FFR 그룹이 IVUS 그룹에 비해 열등하지 않음을 평가하기 위해 비열등성 검정을 시행했으며, 비열등성 허용치는 2.5%포인트로 설정

---

## Results

- PCI 시행 비율은 FFR 그룹에서 44.4%, IVUS 그룹에서 65.3%
- 24개월 시점에서 주요 결과 사건(사망, 심근경색, 또는 재혈관화)이 발생한 비율은 FFR 그룹에서 8.1%, IVUS 그룹에서 8.5%
- 두 그룹 간의 절대 차이는 –0.4%포인트, 단측 97.5% 신뢰구간의 상한은 2.2%포인트(P=0.01, 비열등성 기준 충족)
- 환자가 직접 보고한 결과(Seattle Angina Questionnaire에 기반한 협심증 관련 증상 평가지표)는 두 그룹 간에 유사

---

## Conclusions

중간 정도 협착이 있는 환자에서 PCI 여부를 평가할 때, 24개월 동안 사망, 심근경색 또는 재혈관화로 구성된 복합 주요 결과에 대해 FFR 유도는 IVUS 유도에 비해 비열등함이 입증

---

## 연구 목적

- 중등도 협착(40-70%)을 보이는 CAD 환자들에 대해,
- PCI 수행 기준과 유도에 있어
- FFR 단독 사용군과 IVUS 단독 사용군을 비교하여,
- FFR 사용이 IVUS에 대해 비열등한지를 평가

---

## 연구 설계

- 연구자 주도, 전향적, 무작위배정, 공개표지, 다국가 임상시험
- 한국과 중국 18개 기관

---

## 대상 환자 및 무작위 배정

- 포함 기준
  - 19세 이상
  - 허혈성 심장질환이 의심되고,
  - 관상동맥 조영술상 표적 혈관의 직경이 시각적 추정으로 2.5mm 이상인,
  - 새로운 중등도 협착(40~70%)이 확인된 경우

---

## 대상 환자 및 무작위 배정

- 제외 기준
  - 심장 이외의 질환으로 기대 여명이 2년 미만인 경우
  - 표적 병변이 좌주간동맥 또는 coronary bypass graft에 위치한 경우
  - 출혈 위험이 높은 경우

- 1:1 concealed randomization

---

## 재혈관화 시행 기준 및 PCI 성공 기준

FFR 기준:

- 시행 기준: FFR ≤ 0.80
- 성공 기준: PCI 후 FFR ≥ 0.88 또는 스텐트 전후 FFR 차이 < 0.05

---

## 재혈관화 시행 기준 및 PCI 성공 기준

IVUS 기준:

- 시행 기준: 최소 혈관 내 면적(MLA) ≤ 3 mm²
- 또는 3 < MLA < 4mm² 이면서 플라크 burden ≥ 70%
- 성공 기준: 스텐트 가장자리의 플라크 burden ≤ 55%, 최소 스텐트 면적 ≥ 5.5 mm²

---

## 평가 지표 및 정의

- Primary outcome: 사망, 심근경색, 모든 재혈관화의 복합지표 (24개월 기준)
- Key secondary outcome: 각 항목의 개별 요소, 환자, 혈관별 스텐트 개수, 뇌졸증, 환자 보고 결과(Seattle Angina Questionnaire, SAQ)
- SYNTAX (Synergy between Percutaneous Coronary Intervention with Taxus and Cardiac Surgery) score

---

## 통계 분석

- 표본 크기 산정:
  - 24개월 후 primary outcome 발생률: FFR군 10%, IVUS군 12%로 가정
  - 비열등성 한계(noninferiority margin): 2.5%
  - 검정력(power): 90%
  -  one-sided 95% confidence interval, 5% type I error rate
  
- 연속형 변수: 평균, 표준편차
- 범주형 변수: 총 개수, 백분율

---

## 통계 분석

- Primary outcome
  - Cox proportional-hazards model 사용
  - random effect로 아래 두 변수 포함:
    - 임상시험 실시 기관
    - 당뇨병 유무
  - 사건 발생 시간 분석: Kaplan–Meier method 적용

---

## 통계 분석

  - proportional-hazards model: Schoenfeld 잔차에 대한 양측 검정(P=0.05)
  - 추적관찰 누락된 경우: 검열(censored) 자료로 처리
  - 분석 단위: 환자 단위 및 혈관 단위
  - 분석 집단: Intention-to-treat(ITT), Per-protocol(PP) 방식 모두 사용

---

## 통계 분석

- Key secondary outcome
  - 다중 비교 보정은 실시하지 않음
  - 결과는 점 추정치와 양측 95% 신뢰구간으로만 보고
  - 신뢰구간 폭은 다중 비교 조정이 반영되지 않아, 결정적 치료 효과를 해석하는 데 부적절

---

## 주요 결과

- PCI 시행률:
  - FFR 그룹: 44.4%
  - IVUS 그룹: 65.3% (FFR 대비 유의하게 높음)

- 스텐트 사용량 (PCI 시행 환자 기준):
  - 평균 스텐트 수: FFR 1.4개 vs. IVUS 1.5개
  - 평균 스텐트 길이: FFR 37.2mm vs. IVUS 38.6mm (두 집단 유사)

- 혈관 별 기준으로는 PCI 시행 비율이 IVUS가 더 높음

---

## 주요 결과

- Primary outcome
  - FFR 그룹: 67명 (8.1%)
  - IVUS 그룹: 71명 (8.5%)
  - 절대 차이: –0.4%p

- 비열등성 분석 결과:
  - 단측 95% 신뢰구간 상한: 1.8%p
  - 단측 97.5% 신뢰구간 상한: 2.2%p
  - 비열등성 기준 2.5%p를 초과하지 않아 비열등성 입증(P값: 0.01)

---

## 주요 결과

- Cox 비례위험 모형 가정 검정:
  - Schoenfeld 잔차에 대한 글로벌 검정 결과: P = 0.99

- SAQ 점수:
  - 5개 도메인 모두에서 양 군 유사
  - 증상 완화 및 삶의 질 개선 정도에 차이 없음

---

## Discussion

- 스텐트 사용 및 자원 효율성
  - IVUS 그룹은 스텐트 사용 사용 빈도가 더 높음
  - FFR 그룹은 불필요한 시술 및 자원 사용이 줄어듦

---

## 한계점

- 대상 환자 대부분이 저위험군 (SYNTAX 점수 평균 <10) → 고위험군에는 적용 어려움
- 연구자가 배정군을 알고 있었음 → 재혈관화 판단에 의도치 않은 편향 가능
- 시술 기준과 성공 기준은 고정된 값을 사용 → 병변 특성 및 해부학적 다양성 반영 어려움
- FFR과 IVUS 외의 기술들(OCT, NIRS 등)은 고려되지 않음
- 연구 대상은 모두 아시아인 → 다른 인종에 대한 외삽 어려움